/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "djypkcyqogiwwxzbueyx"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqeXBrY3lxb2dpd3d4emJ1ZXl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc2NzgwNDMsImV4cCI6MjA5MzI1NDA0M30.NWGRHZ7qPirsZW2C-g-umoTihw9NmP9dn12-_ZK0PVU"